// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBotIhSUkF5qoZ50Hv8deTCb2zI98PyHKs',
    appId: '1:80492426112:web:53ec00eedc1ef0c37d8765',
    messagingSenderId: '80492426112',
    projectId: 'innerbloom-8455a',
    authDomain: 'innerbloom-8455a.firebaseapp.com',
    storageBucket: 'innerbloom-8455a.firebasestorage.app',
    measurementId: 'G-MY8C0Q1PW5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRm4wn7gkuehGeMLSJgoyRspZB24YKu-o',
    appId: '1:80492426112:android:76829ea862b0e2d87d8765',
    messagingSenderId: '80492426112',
    projectId: 'innerbloom-8455a',
    storageBucket: 'innerbloom-8455a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_C96gK1Jmj96wklYTJ78vGeI3xyDAEb0',
    appId: '1:80492426112:ios:df30a15ebe7e14097d8765',
    messagingSenderId: '80492426112',
    projectId: 'innerbloom-8455a',
    storageBucket: 'innerbloom-8455a.firebasestorage.app',
    iosBundleId: 'com.example.innerBloomApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_C96gK1Jmj96wklYTJ78vGeI3xyDAEb0',
    appId: '1:80492426112:ios:df30a15ebe7e14097d8765',
    messagingSenderId: '80492426112',
    projectId: 'innerbloom-8455a',
    storageBucket: 'innerbloom-8455a.firebasestorage.app',
    iosBundleId: 'com.example.innerBloomApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBotIhSUkF5qoZ50Hv8deTCb2zI98PyHKs',
    appId: '1:80492426112:web:b82652af8dfdb4a27d8765',
    messagingSenderId: '80492426112',
    projectId: 'innerbloom-8455a',
    authDomain: 'innerbloom-8455a.firebaseapp.com',
    storageBucket: 'innerbloom-8455a.firebasestorage.app',
    measurementId: 'G-W7B43Q824T',
  );
}
